### ISSUE TITLE
Broken link to Contributing.md

### ISSUE THREAD

**Issue by PadreSVK** [learn-anything/learn-anything#10]
### Bug 🐞

Broken link on "about" modal, link refer to https://github.com/learn-anything/learn-anything/blob/dev/CONTRIBUTING.md#contributing, it could be https://github.com/learn-anything/learn-anything/blob/new-start/CONTRIBUTING.md

### Steps to Reproduce:

1. https://learn-anything.xyz/programming/programming-languages
2. ![image](https://user-images.githubusercontent.com/8254631/70372648-02fc8300-18e2-11ea-8ec6-e11d08dadeab.png)

**Comment by nikitavoloboev** [comment]
We are rebuilding the site now.
