### ISSUE TITLE
Labels on maps clumped together

### ISSUE THREAD

**Issue by BoredBored** [learn-anything/learn-anything#1213]
On some maps certain labels are intersecting; 
For example:
https://learn-anything.xyz/web-development/front-end/css/css3
https://learn-anything.xyz/operating-systems/unix/linux/distributions
https://learn-anything.xyz/web-development/content-management-systems
https://learn-anything.xyz/mathematics/statistics/probability-theory/distributions
https://learn-anything.xyz/mathematics/logic/propositional-logic
https://learn-anything.xyz/mathematics/statistics/probability-theory
https://learn-anything.xyz/philosophy/ethics
https://learn-anything.xyz/programming/programming-languages/php
https://learn-anything.xyz/infrastructure
https://learn-anything.xyz/computer-science/algorithms/graph
https://learn-anything.xyz/engineering/electrical-engineering/electronics/electronic-circuits
https://learn-anything.xyz/philosophy/philosophy-of-mind/consciousness
https://learn-anything.xyz/mathematics/geometry/coordinate-systems
https://learn-anything.xyz/marketing

**Comment by nglgzz** [comment]
Yep, that problem should be mostly solved on the new version that is coming soon. 

Thank you for taking the time to point this out 🙏

**Comment by nikitavoloboev** [comment]
Hey @BoredBored 

You can check our our [new version of Learn Anything](https://learn-anything.xyz). Let us know what you think of it and we hope this solves your problem. 🙂
