### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by mattdax** [learn-anything/learn-anything#1216]
Instructions for cloning and setting up Learn Anything are outdated and need updates.
- [x] Dynamo Db download
- [x] Dynamo run command
- [ ] Setup instructions for other Operating Systems
- [ ] API Documentation
- [ ] Other setup requirements

**Comment by jeremyboom8** [comment]
Hey Nikita and collaborators, awesome project 🤓 Why not put it up on https://opencollective.com?

**Comment by nikitavoloboev** [comment]
Hey @jeremyboom8 

Thank you for your kind words. We were deciding between Open Collective and Patreon but decided to go with [Patreon](https://patreon.com/learnanything).
