### ISSUE TITLE
Demo site doesn't work

### ISSUE THREAD

**Issue by kriku** [learn-anything/learn-anything#1218]
![2017-12-03-18 32 07](https://user-images.githubusercontent.com/6429161/33526869-2c30b6fa-d858-11e7-8d42-afd5eab03802.png)

(Mozilla Firefox 57.0 for Arch Linux)

![2017-12-03-18 38 57](https://user-images.githubusercontent.com/6429161/33526929-2bfbb0da-d859-11e7-804a-0723b0533b78.png)

(Chromium)

**Comment by nglgzz** [comment]
Try again now ❤️

**Comment by nglgzz** [comment]
I was deploying the new version, now it's up, let us know how you like it.

**Comment by kriku** [comment]
Actually pretty cool :)

Works well

**Comment by nglgzz** [comment]
Awesome! Happy to hear that you like it :)
