### ISSUE TITLE
Some bubbles/labels are not shown on the web page

### ISSUE THREAD

**Issue by BoredBored** [learn-anything/learn-anything#1220]
In https://learn-anything.xyz/operating-systems/unix/linux/distribution at the top there are some not shown

**Comment by ximet** [comment]
I can help you with this bug

**Comment by nglgzz** [comment]
Hey @ximet, that would be awesome! The problem should be [here](https://github.com/learn-anything/learn-anything/blob/master/client/components/map/Map.jsx). I think the component we're using for moving around the SVG map has some sort of block when you reach the boundaries of the map, so you could check if there's a way to deactivate that.
