### ISSUE TITLE
Add ability to Favourite or Star resources

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/learn-anything#1223]
I would really love if you could not only upvote and downvote resources but also `Favourite` them. 

This way, you can go to any topic and will be able to see which resources do you want to use for learning the topic and you don't have to save them anywhere in your notes or anywhere else.

Perhaps we can add a little star next to the resource that when clicked, will add the resource to your `favourites`.

**Comment by tomzx** [comment]
In the same vein of ideas, it would be nice to be able to leave a trace on the resources we've seen.
