### ISSUE TITLE
Add the ability to "save" resources for later reading.

### ISSUE THREAD

**Issue by jazzminewang** [learn-anything/learn-anything#1224]
A follow-up would be to create custom self-education playlists. :)

**Comment by nglgzz** [comment]
I really love this idea. Would be really cool to be able to share these playlists and search for public playlists.

**Comment by k9triz** [comment]
Doesn't youtube already do this?

**Comment by nglgzz** [comment]
Yeah we maybe chose the wrong term. For "playlists" I think we meant lists of saved resources, which could be Youtube videos, but could also be anything else (blog articles, books, courses and so on).

**Comment by Beastjdhr** [comment]
Hey, I'd like to work on implementing this feature. Is it still open?
