### ISSUE TITLE
Add Random Button to search 

### ISSUE THREAD

**Issue by sherxon** [learn-anything/learn-anything#1225]
Is it possible to add **Random** button for those who are interested to learn random topics

**Comment by nikitavoloboev** [comment]
The website suggests you a random topic to learn every time you open the website. 

It is in greyed out text like here: 

![2017-12-11 at 03 34](https://user-images.githubusercontent.com/6391776/33813464-3a9b39d2-de24-11e7-8e74-e738bb7d4229.png)

The suggestion is to learn `graphic design`. If you press enter graphic design map opens.

**Comment by sherxon** [comment]
oh,  right!  thank you :)
