### ISSUE TITLE
Random Topic

### ISSUE THREAD

**Issue by dpollard-gva** [learn-anything/learn-anything#1230]
Hi,

New user here, went to your site and had no idea what to even begin to search. Could you perhaps make a button that is similar to Google's "I'm feeling lucky" only when clicked it, takes 1 of the top 100 searched topics and spits out results for it.

I would be open to also helping develop this new feature as a contributor.

Thanks 
Derek

**Comment by nglgzz** [comment]
Hey @dpollard-gva, on the main page if you don't type anything and press enter the map indicated on the placeholder will open. 

![image](https://user-images.githubusercontent.com/13448636/33858455-f58414e8-decf-11e7-8bfc-5d6e27ce3e15.png)

For example in this image the random topic would be algorithmic trading.

Seems like this is not very intuitive though, as you're the second person pointing this out. Do you have any suggestion on how to make this more clear? Perhaps explaining this on the help text below the search bar could help?

Thank you
Angelo

**Comment by dpollard-gva** [comment]
Yes, that's perfect!

**Comment by dpollard-gva** [comment]
What about going with a more google-ish style search setup
<img width="737" alt="googleish" src="https://user-images.githubusercontent.com/33030698/33907675-8ee21240-df4b-11e7-9a4e-ac5c5e279b63.png">

Where, if you click enter while still in the textbox, it will search, but also, clicking the `Google Search` button will do the same.  Also, doing the same with an `I'm feeling lucky`-esque random search button.

**Comment by nglgzz** [comment]
Yeah that's a good idea, it's more intuitive that way. Only thing is that it needs to work well on mobile too, maybe still something Google-ish like this 
![image](https://user-images.githubusercontent.com/13448636/33964483-e8940772-e058-11e7-9c11-88616a36c7a4.png)

Right now this is not top priority, so I may come back to it in a while. If you want to try implementing it yourself though, you're very welcome to do so. I would add the buttons in the  `client/containers/Home.jsx` file.

**Comment by nikitavoloboev** [comment]
I will close this for now as I think the current UI should be obvious enough that the suggested topic if activated on will be opened. No need to complicate the UI more.
