### ISSUE TITLE
About how to improve the map

### ISSUE THREAD

**Issue by kevinskywalker** [learn-anything/learn-anything#1232]
Hello there,

I love your design and idea, but when I tried to improve some map on Finance topic, it comes really confusing to me, I.e: creating a new sub-node for the topic, I think the structure of the map itself is quite important for this design, And I really hope there is a way to help that.

Cheers

**Comment by nikitavoloboev** [comment]
Hey @kevinskywalker 

I agree with you that map structure is really important to get right and that's something we are thinking about right now. We want to make the maps very similar and as least confusing as possible. 

I will try to sketch one example map layout we can use and enforce but I am open to your ideas too on how we can make it better. 🙂

**Comment by nikitavoloboev** [comment]
The new layout can be roughly seen here: https://balsamiq.cloud/svp9z/p20pi/r2278

It's not final but it shows the direction with which we are going. The design should ideally be clear in so far as how users can improve it and contribute to it. 

Feel free to ask any questions on it if you have. @kevinskywalker
