### ISSUE TITLE
Can't see avatar in "Current team"

### ISSUE THREAD

**Issue by HenkeDaniil** [learn-anything/learn-anything#1233]
https://i.imgur.com/ukDvtoQ.png

**Comment by nikitavoloboev** [comment]
Hey @HenkeDaniil 

Which browser are you using?

**Comment by HenkeDaniil** [comment]
@nikitavoloboev 
Firefox Quantum 
57.0.1(64-bit)

**Comment by nikitavoloboev** [comment]
Thank you for spotting that. Will be fixed right now 🙂
