### ISSUE TITLE
hierarchical relationship between topics

### ISSUE THREAD

**Issue by sfqdtc** [learn-anything/learn-anything#1234]
Hi guys , I found your website on some social media and I think your idea is awesome. People told me we can improve the website without code , but i only saw several seconds of improving introduction in the video that you made , and i think the next window that came up was still code (around 5:40 in the video ) . For me after I clicked the improve button , even the instructions didn't show up . I am not sure if is due to the safari browser .  meanwhile , I am curious about how you define hierarchical relationship between the topics . actually I think I have already seen some wrong hierarchical relationship topics .

cheers

**Comment by nikitavoloboev** [comment]
Hey @sfqdtc 

Apologise for things being unclear for how to improve the maps. We are going to release a new YouTube video today to clear everything up.

Also there is indeed an issue with Safari browser that we also need to fix. The green buttons to add resources are not showing fully on Safari.

> I am curious about how you define hierarchical relationship between the topics

The hierarchical relationship between the topics is defined in a way that ideally covers dependencies of each of the topics but also closest relation to another topic. The simplest example would be `Python` being put inside `Programming languages`.

**Comment by sfqdtc** [comment]
Hi , thx for the reply , hope I can use it on safari asap . And I understand what you just said about hierarchical relationship , but what is my doubt is have you got a solution to examine the hierarchical relationship that created by the user . cause I have seen some wrong relation now .  since I am not a coder , so I don't know whether my expression is accurate , if my question mislead you sorry for that .

**Comment by nikitavoloboev** [comment]
Hi @sfqdtc. We are working on new design for the website. Rough idea of how it will look can be seen here: https://balsamiq.cloud/svp9z/p20pi/r2278

Let us know what you think of it @sfqdtc. We really appreciate any feedback. 🙂
