### ISSUE TITLE
I added something to Javascript Programming Language at the wrong place, please move

### ISSUE THREAD

**Issue by bmix** [learn-anything/learn-anything#1236]
I added 'Tracing Javascript's Prototype Chain' at the main node for the 'Javascript Programming Language'. It does not belong there. Sorry. Could you, please, add a new node 'Objects' and place it there? Thanks.
Would be nice if I'd could do these myself, but I guess you are working on such a thing already.

**Comment by nglgzz** [comment]
Sure thing, will do that now! 

Yeah it's on the list of things we need to do 😄

**Comment by nglgzz** [comment]
Done 😃
