### ISSUE TITLE
Topics not returned via search bar

### ISSUE THREAD

**Issue by feocco** [learn-anything/learn-anything#1237]
Ignore

**Comment by nikitavoloboev** [comment]
Hey @feocco 

For me Python is third suggestion:

![2017-12-18 at 19 55](https://user-images.githubusercontent.com/6391776/34122631-671ecfaa-e42d-11e7-8991-61e2b4724c52.png)

I do agree though that current suggestions need to be improved a lot since you can't find some topics.

**Comment by feocco** [comment]
Yeah - I was comparing the topic page title "Python" and just completely ignored the longer text with "programming language" included. That addition is actually convenient - just not expected. My apologies for the false report.
