### ISSUE TITLE
Security Concern On The Web Page

### ISSUE THREAD

**Issue by antoaravinth** [learn-anything/learn-anything#1239]
Hello, 

Thanks for the nice project. Looks like the website doesn't follow any security practices like csp, csrf, referrer policy etc. I guess these are just required for any website, since learn anything supports Google Auth etc, without these security measure its easy for the attacker to inject a script and take away tokens etc which would be a serious security breach. 

May be I'm missing something here?

Thanks.

**Comment by nglgzz** [comment]
Hey @antoaravinth, 

Thank you for bringing this up! I didn't know about those practices. Do you have links to resources explaining how and what I should implement to make the website more secure?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (112/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:58447 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eWpnP-0036Xn-Qr
	for greg@biomassiv.es; Wed, 03 Jan 2018 14:37:55 -0600
Date: Wed, 03 Jan 2018 12:37:16 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1515011836;
	bh=ZyoHfAGwfxdRnP75hpQf5pX/8iaTlOTUjvLzz63JDHE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=nym80rtL6KhVQAxAsSACIqsKLX/PMGSbaVDM3rJwiy41SJb43A6sm226NA1dBlAi4
	 If142glt3WKEJK3VXY1IopajwWulUeJtVl2eJ/hUheHjCV7y76Y8ttw5fLGU/V2Rry
	 iu6gd+meiz4PLgYvhlQ9GqNhBYtxIc0wXagCrFc4=

**Comment by antoaravinth** [comment]
@nglgzz Hello, thanks for your response. I wouldn't call myself an security expert, but we are using projects like https://github.com/krakenjs/lusca, which implements these practices. This works really well in real world (its open sourced by paypal).

I'm afraid we can't use lusca, as we are not using express-session, express-cookie. However, finding and enabling these security concepts on any express should be straight forward. I can take this up and work on my free time.

**Comment by nglgzz** [comment]
Okay I'll have a look at lusca, and I'll try to search if there's something similar that we can use. 
In the meantime if you want to work on this issue it would be very much appreciated :)

**Comment by Katamori** [comment]
Seconded. Beyond a certain level, you should consider security procedures.

**Comment by antoaravinth** [comment]
@nglgzz . I was looking at this issue and I want few information from you. 

1. Protections like CSP, X-Frame-Options are heavily supported by browsers, its just we need to set the correct headers from the server side. These headers specify certain rules, which allows the browser to render/execute scripts from certain endpoint. So, I want to understand, in our front-end code, all the dependencies are bundled in a single shot js or we are pulling out js @ runtime? If so we need to specify what all sites we can allow for the browser to download and execute the scripts. 

Also, I want to understand whether are we using `eval` in our codebase? Because CSP, can block that as well.

**Comment by nglgzz** [comment]
All dependencies are bundled. The only exceptions are the fonts (https://fonts.googleapis.com/)  and the Google Analytics code (https://www.googletagmanager.com). Also we're not using `eval`.

**Comment by antoaravinth** [comment]
@nglgzz Hello, I'm trying to figure out the CSP headers and I came up with this:

```
Content-Security-Policy: default-src 'none'; img-src 'self'; style-src https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self' 'sha256-P5doNkGIYPY4buNz4F3MZTuGkfWgTnegaH1gjaiSrmM=' https://www.googletagmanager.com
```

I want to understand, how we are hoisting the bundle.js generated by webpack. Because, we are not going to add CSP headers (or any other security headers) in development mode; so just in production, we need to ask our express sever to set these headers correctly, so I want to understand, how do we do the deployment in prod.

**Comment by nglgzz** [comment]
Hi @antoaravinth, the bundle.js file is served with the rest of the static files on line 44 of the `server/index.js` file.

    app.use('/static', express.static('client/dist'));

 It works the same both on development and in production. You can use the [setHeaders](http://expressjs.com/en/api.html#setHeaders) option to set the header only on static files, and you can check for the NODE_ENV environment variable to add the headers only in production (the variable will be set to `production` if it's running in production, anything else is development).

**Comment by antoaravinth** [comment]
Guess it can be closed. Thanks for your help @nglgzz !
