### ISSUE TITLE
Not possible to add a resource due to div overlapping

### ISSUE THREAD

**Issue by tomzx** [learn-anything/learn-anything#1240]
In the attached image, you can see that it is not possible to click on the "Add a new resource" link of the "Basics" node.

https://learn-anything.xyz/cognitive-science/cognition/cognitive-biases

![chrome_2018-01-13_21-28-10](https://user-images.githubusercontent.com/188960/34912197-b6dfa192-f8a8-11e7-9e6e-8da99fdcb5d4.png)

**Comment by Likivik** [comment]
On Firefox even worse
![image](https://user-images.githubusercontent.com/11075952/35861131-aae67232-0b57-11e8-8c53-d133f257558f.png)

**Comment by nikitavoloboev** [comment]
Hey @tomzx and @Likivik. This problem will go away with the new design we are working on which can be seen here https://balsamiq.cloud/svp9z/p20pi/r2278. The design is a rough idea but it shows the direction in which we are going.

We welcome any feedback on it.
