### ISSUE TITLE
Display already voted on items

### ISSUE THREAD

**Issue by tomzx** [learn-anything/learn-anything#1241]
On page load and page transition, the items on which the user already has voted should have their vote value already displayed.

I vote
![chrome_2018-01-13_21-35-50](https://user-images.githubusercontent.com/188960/34912228-c28bafa8-f8a9-11e7-8ad6-13cf28c8917a.png)

I refresh the page
![chrome_2018-01-13_21-36-09](https://user-images.githubusercontent.com/188960/34912231-d4a7bbaa-f8a9-11e7-9053-333c152d75b0.png)

I click on the + again
![chrome_2018-01-13_21-35-50](https://user-images.githubusercontent.com/188960/34912228-c28bafa8-f8a9-11e7-8ad6-13cf28c8917a.png)

**Comment by nikitavoloboev** [comment]
This is a bug that should be solved with the new design. We hope to find a good answer to #1243 problem first though.
