### ISSUE TITLE
Editing existing items

### ISSUE THREAD

**Issue by tomzx** [learn-anything/learn-anything#1242]
It is currently only possible to add new resources, but what about editing existing resources that have a bad title, or removing dead resources?

**Comment by KeyJoo** [comment]
Most likely this privilege will remain behind the core of developers.

**Comment by nikitavoloboev** [comment]
In new design we are working on, there will be ability to report resources that user deems incorrect or inappropriate. The moderators of the topic should then be able to deal with the resource appropriately in case it is indeed inappropriate.

I believe this should solve this issue. Let me know if you think we can solve this better.
