### ISSUE TITLE
Installing it

### ISSUE THREAD

**Issue by halsuga** [learn-anything/learn-anything#1248]
Is there a way to use parts of the app and modify it for one's own purposes?  Like to do training etc on one's own server?  How would I install it?  Do I simply follow the instructions on the contributing page?

**Comment by nglgzz** [comment]
Hey @halsuga! Yes, it's possible to do that. To install it you can simply follow the instructions on the [contributing page](https://github.com/learn-anything/learn-anything/blob/dev/CONTRIBUTING.md). If you have any problems feel free to open a new issue.

Have fun!
