### ISSUE TITLE
Sorting method of nodes

### ISSUE THREAD

**Issue by Mister-GoodwinLu** [learn-anything/learn-anything#1249]
the nodes seem haphazardly sorted; some items are close due to being closely related, but overall the subjects seem randomly scattered, I believe (math on the right, other on the left). Maybe there should be an option to also alphabetize in order to have a different sorting method so we know where to look for a subject

**Comment by nikitavoloboev** [comment]
New design will break away resources away from the map visualisation.

The topics will be visualised in an open graph way and the topics will be presented in a more typical web page similar to a Reddit subreddit. This of course can change as we find better way to do implement it as we work on the new design, which you can certainly help us with. 🙂 

For information on how new design looks, you can see the VOD [here](https://www.twitch.tv/videos/227357172).
