### ISSUE TITLE
Add general sites

### ISSUE THREAD

**Issue by Mister-GoodwinLu** [learn-anything/learn-anything#1250]
There are a lot of general research sites for a starting point, for example, Wikipedia.org is the most basic one (though it probably is too well known to be useful when listed here). However, http://www.openculture.com/freeonlinecourses on the other hand is far more obscure but arguably more helpful, since Wikipedia only cites hundreds of sources with occasional professional editing rather than being actual courses having structure and trained professors.

What do you think? Are websites like /freeonlinecourses far too few and between for "generic sites" similar to learn-anything?

**Comment by nikitavoloboev** [comment]
The current goal of LA is to visualise different topics connecting them together and curating the best resources available for learning the topics in context of what the person already knows.

Open Culture is just one resource of many that can be used to learn things though.
