### ISSUE TITLE
Native app to track things to learn and things learning

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/learn-anything#1257]
I've been thinking how awesome it would be to have a native app focused purely on tracking things I'm learning and things I want to learn with integration to LA. Native because I plan to use the app very often as I imagine using it to break up projects I want to build into things I want to learn for that. 

For this to work, LA simply needs to provide the necessary API endpoints for storing topics I want to learn, topics existing in LA database + ability to add custom topics and ability to fetch me with curated plans for each of the topics so I don't have to do any searching myself. 

Building a native or our own LA web interface for this would then be quite doable and awesome.

**Comment by nglgzz** [comment]
I guess we could add an API that would work like a wish list. Where you add topics you want to learn, and it shows you study plans for those topics. I can see this being useful for an app like the one you mention. It would be a different service though, so it might be more appropriate to have it on a separate repository.

In any case this is not the main priority right now (as we don't have any API for the new version yet).
