### ISSUE TITLE
Browser incompatibilities - Blank page in Safari; links are unusable in Brave Browser

### ISSUE THREAD

**Issue by the-sushi** [learn-anything/learn-anything#1280]
**Bug report**

In Safari 11.1.2 (with uBlock Origin installed, same behavior when disabled though), when the site is loaded, a blank page is displayed instead of the actual site. 
In Brave Browser 0.57.6 Beta, the links from the first box all point to the URLs of the links in the second. 

**What actions did you take?**
Safari: Opened https://learn-anything.xyz, disabled uBlock Origin and repeated the process
Brave: Opened https://learn-anything.xyz, searched 'linear algebra', tried to click on links in first map box.  Also tried other pages, got the same result

**What is the expected behavior?**

Should load the page in Safari, and links should be properly set in Brave.

**What is the current behavior?**

In Safari, only a blank page is shown.  In Brave, hovering over and clicking items in the first box acts as though I were doing it in the box to the right and lower of it.

**Reasons?**

Mouse offset in Brave? In Safari, the body section of the page is empty aside from `<div id="react-app"></div>` and `<script nonce=​"random-looking-string" src=​"/​static/​en.bundle.js">​</script>​`

**Comment by nikitavoloboev** [comment]
Thanks for the report.

We are working on a new version of the website that is rewritten from scratch. We will make sure to not have these kinds of issues in the new version.
