### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by kosciak9** [learn-anything/learn-anything#1291]
**Bug report**

https://learn-anything.xyz/ displays 404 nginx error. Docs site is fine though.

**What actions did you take?**

Just visited it through Firefox and Chromium.

**What is the expected behavior?**

Site works. :)

**What is the current behavior?**

404!

**Comment by nikitavoloboev** [comment]
Will be up shortly. 😅

**Comment by nglgzz** [comment]
Should be fixed now.
