### ISSUE TITLE
Docker Compose example

### ISSUE THREAD

**Issue by almereyda** [learn-anything/learn-anything#1292]
**Feature Request**

Add a `docker-compose.yml` example.

**What feature do you want to see?**

This feature provides a canonical example of a service setup to run learn-anything standalone.

**Why do you want to see this feature?**

For easy replication of a running `learn-anything` environment by third-parties.

**How will this feature benefit users/devs?**

This helps to bootstrap an isolated learn-anything development environment locally, and allows administrators to learn from a canonical example to run a production `learn-anything` instance.

**Comment by almereyda** [comment]
This can be directly adapted from https://github.com/learn-anything/learn-anything/blob/master/.circleci/config.yml

**Comment by nikitavoloboev** [comment]
We will add this when the new version of LA will be live.
