### ISSUE TITLE
Add page for creating study guides

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/learn-anything#5]
## Feature Summary ✨

When a user presses the button to `Create a study guide`, study guide creation page should be shown to the user.

## Why do we need this?

Essential feature as without it no study guides can be created.

## How do you propose to implement this?

There is [Figma mockups](https://www.figma.com/file/N2ioUbr7aiapNijNH8DH3Xh3/1.0?node-id=465%3A128) made by @johnletey already. Preview:

![/guide/new/](https://user-images.githubusercontent.com/30328854/63014555-b26e9f00-be86-11e9-84a2-6aaa30cb0c82.png)

We can start with that and implement the required logic we need to store the user input from the page on the backend and in our database.

Need to think how we will serialize the study guides and what data structures will be used.

**Comment by ChristianMMacy** [comment]
Hi @nikitavoloboev ! I was considering contributing to the project and thought I'd start by sharing that the link on "Figma mockups" results in a 404--at least for me :-)

**Comment by johnletey** [comment]
@ChristianMMacy Thanks for reporting! Can you please try this [link](https://www.figma.com/file/N2ioUbr7aiapNijNH8DH3Xh3/1.0?node-id=465%3A128)?
