### ISSUE TITLE
no maps are being displayed on Edge browser

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/learn-anything#54]
As reference to this issue : https://github.com/nikitavoloboev/learn-anything/issues/1062

**Comment by nglgzz** [comment]
Are there any errors in console?

**Comment by yingwei13mei** [comment]
Also have the same problem on Edge and Chrome, have the bug been fixed ？
And there is no error in console. 

"
  [234] ./client/sass/main.sass 1.28 kB {0} [built]
  [237] external "ReactRouterDOM" 42 bytes {0} [not cacheable]
  [239] multi webpack-hot-middleware/client?reload=true&timeout=2000 react-hot-loader/patch ./client/index.jsx 52 bytes {0} [built]
     + 225 hidden modules
webpack: Compiled successfully.
"

**Comment by nglgzz** [comment]
Apparently Edge [doesn't like self closing SVG tags](https://stackoverflow.com/questions/24299969/closing-svg-tags-explicit-or-self-closing), I'm gonna have a look at this on the weekend.
