### ISSUE TITLE
fix contribute button

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/learn-anything#73]
It broke after ES update. Should link to correct file.

**Comment by Jedeu** [comment]
Hi @nikitavoloboev could you please describe exactly what the expected outcome is? Where would I normally find the contribute button on https://learn-anything.xyz/ ?

**Comment by nglgzz** [comment]
You find it in the bottom right on each map. It's the orange button saying "Improve this map". In the code you can find it in `client/components/ContributeButton.jsx` and it's being rendered in `client/containers/Pages.jsx`.

**Comment by nikitavoloboev** [comment]
Hey @Jedeu also for expected outcome. This button at the end of this contribute dialogue box : 

![2017-10-01 at 10 22](https://user-images.githubusercontent.com/6391776/31052978-6b8d1994-a692-11e7-8911-965bac1c488c.png)

Should link to the appropriate JSON file in [maps](https://github.com/learn-anything/maps) repository. So for [front end map](https://learn-anything.xyz/web-development/front-end), contribution will lead to [here](https://github.com/learn-anything/maps/blob/master/learn-anything/web-development/front-end.json).
